routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'GuestController@index')->name('index');

// Route::get('/blog-single', function () {
//     return view('blog-single');
// });

Route::get('/pricing', function () {
    return view('price');
});
Route::get('/recherche', 'GuestController@search')->name('guest.search');
Route::get('/boutique-du-jour', 'GuestController@shop_of_z_day')->name('guest.shop_of_z_day');

Route::get('/blog', 'GuestController@index_blog');
Route::get('/blog/{slug_categorie_blog}', 'GuestController@blog_categorie_index')->name('guest.blog-index');
Route::get('/blog/{slug_categorie_blog}/{slug_article}', 'GuestController@blog_index')->name('guest.blog-index-item');
Route::get('/categorie', 'GuestController@categorie');
Route::get('/boutique/{slug_nom_boutique}', 'GuestController@boutique_index')->name('guest.boutique-index');
Route::get('/boutique/{slug_nom_boutique}/{slug_nom_produit}', 'GuestController@produit_index')->name('guest.produit-index');
Route::get('/categorie/{nom_categorie_boutique}', 'GuestController@categorie_index')->name('guest.categorie-index');


Auth::routes();

// Route Profil CLIENT
Route::middleware(['auth', 'client'])->group(function() {
    // Dashboard
    Route::get('/dashboard', 'HomeController@index')->name('home');
    Route::get('/profil', 'ClientController@profil')->name('client.profil');
    Route::get('/auth_user_update', 'ClientController@update_auth_profile')->name('client.update-auth');
    Route::get('/user-change-password', 'ClientController@update_pwd')->name('client.user-change-pwd');
    Route::get('/boutiques', 'ClientController@index_boutique')->name('client.index-shop');

    Route::get('/produit', 'ClientController@index_produit')->name('client.index-produit');
    Route::get('/boutiques/create', 'ClientController@create_boutique')->name('client.create-shop');
    Route::get('/produit/create', 'ClientController@create_produit')->name('client.create-produit');
    Route::post('/boutiques/store', 'ClientController@store_boutique')->name('client.store-shop');
    Route::post('/produit/store', 'ClientController@store_produit')->name('client.store-produit');
    Route::get('/boutiques/{id}/edit', 'ClientController@edit_boutique')->name('client.edit-shop');
    Route::get('/boutiques/update', 'ClientController@update_boutique')->name('client.update-shop');
    Route::get('/produit/update', 'ClientController@update_produit')->name('client.update-produit');
    Route::get('/produit/{id}/edit', 'ClientController@edit_produit')->name('client.edit-produit');
    Route::get('/removeImageFromGallerie', 'ClientController@removeImageFromGallerie');

    Route::delete('/produit/{id}/delete', 'ClientController@destroy_produit')->name('client.delete-produit');

    //message
    Route::resource('/message', 'MessageController');
});

// Route Profil ADMINISTRATEUR
Route::middleware(['auth', 'admin'])->prefix('admin')->group(function() {
    // Dashboard
    Route::get('/dashboard', 'HomeController@admin')->name('admin');

    // Pack Abonnement resource
    Route::resource('/pack-abonnement', 'PackAbonnementController');

    // Categorie Boutique resource
    Route::resource('/categorie-boutique', 'CategorieBoutiqueController');

    // Sous Categorie Boutique resource
    Route::resource('/sous-categorie-boutique', 'SousCategorieBoutiqueController');

    //  Categorie produit resource
    Route::resource('/categorie-produit', 'CategorieProduitController');

    //  Categorie Blog resource
    Route::resource('/categorie-blog', 'CategorieBlogController');

    //  Categorie Blog resource
    Route::resource('/tag', 'TagController');

    //  Article resource
    Route::resource('/article', 'ArticleController');

    //  Article resource
    Route::resource('/boutique', 'BoutiqueController');

    Route::get('/boutique_statut', 'BoutiqueController@statut')->name('boutique.statut');

    //  produit resource
    Route::resource('/produits', 'ProduitController');

    //  User resource
    Route::resource('/utilisateur', 'UserController');
    Route::get('/profil', 'UserController@profil')->name('utilisateur.profil');
    Route::get('/auth_user_update', 'UserController@update_auth_profile')->name('utilisateur.update-auth');
    Route::get('/user-change-password', 'UserController@update_pwd')->name('utilisateur.user-change-pwd');
    Route::get('/nouveau-admin/create', 'UserController@create_admin');
    Route::get('/edit-admin/{id}/edit', 'UserController@edit_admin')->name('utilisateur.edit-a');
    Route::post('/nouveau-admin', 'UserController@store_admin')->name('utilisateur.store-admin');
    Route::put('/edit-admin/{id}/edit', 'UserController@update_admin')->name('utilisateur.edit-admin');

    Route::get('/nouveau-client/create', 'UserController@create_client');
    Route::get('/edit-client/{id}/edit', 'UserController@edit_client')->name('utilisateur.edit-c');
    Route::post('/nouveau-client', 'UserController@store_client')->name('utilisateur.store-client');
    Route::put('/edit-client/{id}', 'UserController@update_client')->name('utilisateur.edit-client');
    Route::get('/removeImageFromGallerie', 'BoutiqueController@removeImageFromGallerie');

});

app/Models/CategorieProduit.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class CategorieProduit extends Model
{

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'nom_categorie_produit', 'slug_categorie_produit', 'photo_categorie_produit',
    ];
}

app/Http/Controllers/CategorieProduitController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Str;
use App\Models\CategorieProduit;

use Session;

class CategorieProduitController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
         $cat_produits = CategorieProduit::paginate(10);

        return view('Admin.CategorieProduit.index', compact('cat_produits'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('Admin.CategorieProduit.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {

        $this->validate($request, [
            'nom_categorie_produit' => 'required|unique:categorie_produits,nom_categorie_produit',
        ]);

        $categorie = CategorieProduit::create([
            'nom_categorie_produit' => $request->nom_categorie_produit,
            // 'photo_categorie_produit' => $request->photo_categorie_produit,
            'slug_categorie_produit' => Str::slug($request->nom_categorie_produit, '-'),
        ]);
        if($request->hasFile('photo_categorie_produit')){
            $photo = $request->photo_categorie_produit;
            $image_new_name = time() . '.' . $photo->getClientOriginalExtension();
            $photo->move('public/storage/categorie_produit/', $image_new_name);
            $categorie->photo_categorie_produit = '/public/storage/categorie_produit/'.$image_new_name;
        }

        $categorie->save();

        Session::flash('success', 'Une nouvelle categorie de produit vient d\'être crée avec succès');

        return redirect()->route('categorie-produit.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $categorie = CategorieProduit::where('id', $id)->first();
        return view('Admin.CategorieProduit.edit', compact('categorie'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $categorie = CategorieProduit::where('id', $id)->first();

        $this->validate($request, [
            'nom_categorie_produit' => "required|unique:categorie_produits,nom_categorie_produit, ",
        ]);


            $categorie->nom_categorie_produit = $request->nom_categorie_produit;
            $categorie->slug_categorie_produit = Str::slug($request->nom_categorie_produit, '-');

        if($request->hasFile('photo_categorie_produit')){
            $photo = $request->photo_categorie_produit;
            $image_new_name = time() . '.' . $photo->getClientOriginalExtension();
            $photo->move('public/storage/categorie_produit/', $image_new_name);
            $categorie->photo_categorie_produit = '/public/storage/categorie_produit/'.$image_new_name;
        }

        $categorie->save();

        Session::flash('success', 'Une Pack categorie vient d\'être modifié avec succès');

        return redirect()->route('categorie-produit.index');

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $categorie = CategorieProduit::find($id);
        $categorie->delete();

        Session::flash('success', 'La Categorie a été supprimé avec succès');
        return redirect()->route('categorie-produit.index');
    }
}

resources/views/Admin/CategorieProduit/create.blade.php
@extends('layouts.app')
@section('content')
<header id="header" class="main-header header-sticky header-sticky-smart header-style-10 text-uppercase bg-white">
    <div class="header-wrapper sticky-area border-bottom">
        <div class="container-fluid">
            <nav class="navbar navbar-expand-xl">
                <div class="header-mobile d-flex d-xl-none flex-fill justify-content-between align-items-center">
                    <div class="navbar-toggler toggle-icon" data-toggle="collapse" data-target="#navbar-main-menu">
                        <span></span>
                    </div>
                    <a class="navbar-brand navbar-brand-mobile" href="{{url('/')}}">
                        <img src="{{asset('images/logo.png')}}" alt="TheDir">
                    </a>
                    <a class="mobile-button-search" href="#search-popup" data-gtf-mfp="true" data-mfp-options='{"type":"inline","mainClass":"mfp-move-from-top mfp-align-top search-popup-bg","closeOnBgClick":false,"showCloseBtn":false}'><i class="far fa-search"></i></a>
                </div>
                <div class="collapse navbar-collapse" id="navbar-main-menu">
                    <a class="navbar-brand d-none d-xl-block" href="{{url('/')}}">
                        <img src="{{asset('images/logo.png')}}" alt="TheDir">
                    </a>
                </div>
            </nav>
        </div>
    </div>
</header>

<div id="wrapper-content" class="wrapper-content pt-0 pb-0">
    <div class="page-wrapper d-flex flex-wrap flex-xl-nowrap">
        @include('Admin.Layouts.sidebar')

        <div class="page-container">
            <div class="container-fluid h-100">
                <div class="page-content-wrapper d-flex flex-column h-100">
                    <h1 class="font-size-h4 mb-4 font-weight-normal">Categorie Produit</h1>
                    <div class="page-content">
                        <div class="card rounded-0 border-0 bg-white px-4 pt-3 pb-6">
                            <div class="card-header p-0 bg-transparent">
                                <h5 class="card-title text-capitalize">Nouvelle Categorie Produit</h5>
                            </div>
                            <div class="card-body px-0 pt-4 pb-0">
                                <div class="form-update-profile">
                                    <form method="POST" action="{{ route('categorie-produit.store') }}" enctype="multipart/form-data">
                                        @csrf
                                        <div class="form-group mb-2">
                                            <label for="nom_categorie_produit" class="font-size-md text-dark font-weight-semibold mb-1">Nom Categorie <span class="text-danger">*</span></label>
                                            <input type="text" class="form-control @error('nom_categorie_produit') border border-danger @enderror" id="nom_categorie_produit" name="nom_categorie_produit" placeholder="Nom Categorie">
                                            @error('nom_categorie_produit')
                                                <div class="alert alert-danger">Le champ nom categorie produit est obligatoire.</div>
                                            @enderror
                                        </div>
                                         <div class="form-group mb-2">
                                            <label for="photo_categorie_produit" class="font-size-md text-dark font-weight-semibold mb-1">Photo Categorie</label>
                                            <input type="file" class="form-control" id="photo_categorie_produit" name="photo_categorie_produit">
                                        </div>
                                        <button type="submit" class="btn btn-primary btn-block font-size-lg">AJOUTER</button>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="mt-auto pt-6">&copy; 2020 Boutique Senegal. All Rights Reserved.</div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/Admin/CategorieProduit/edit.blade.php
@extends('layouts.app')
@section('content')
<header id="header" class="main-header header-sticky header-sticky-smart header-style-10 text-uppercase bg-white">
    <div class="header-wrapper sticky-area border-bottom">
        <div class="container-fluid">
            <nav class="navbar navbar-expand-xl">
                <div class="header-mobile d-flex d-xl-none flex-fill justify-content-between align-items-center">
                    <div class="navbar-toggler toggle-icon" data-toggle="collapse" data-target="#navbar-main-menu">
                        <span></span>
                    </div>
                    <a class="navbar-brand navbar-brand-mobile" href="{{url('/')}}">
                        <img src="{{asset('images/logo.png')}}" alt="TheDir">
                    </a>
                    <a class="mobile-button-search" href="#search-popup" data-gtf-mfp="true" data-mfp-options='{"type":"inline","mainClass":"mfp-move-from-top mfp-align-top search-popup-bg","closeOnBgClick":false,"showCloseBtn":false}'><i class="far fa-search"></i></a>
                </div>
                <div class="collapse navbar-collapse" id="navbar-main-menu">
                    <a class="navbar-brand d-none d-xl-block" href="{{url('/')}}">
                        <img src="{{asset('images/logo.png')}}" alt="TheDir">
                    </a>
                </div>
            </nav>
        </div>
    </div>
</header>

<div id="wrapper-content" class="wrapper-content pt-0 pb-0">
    <div class="page-wrapper d-flex flex-wrap flex-xl-nowrap">
        @include('Admin.Layouts.sidebar')

        <div class="page-container">
            <div class="container-fluid h-100">
                <div class="page-content-wrapper d-flex flex-column h-100">
                    <h1 class="font-size-h4 mb-4 font-weight-normal">Categorie Produit</h1>
                    <div class="page-content">
                        <div class="card rounded-0 border-0 bg-white px-4 pt-3 pb-6">
                            <div class="card-header p-0 bg-transparent">
                                <h5 class="card-title text-capitalize">Modifier Categorie Produit - {{$categorie->nom_categorie_produit}}</h5>
                            </div>
                            <div class="card-body px-0 pt-4 pb-0">
                                <div class="form-update-profile">
                                    <form method="POST" action="{{ route('categorie-produit.update', [$categorie->id]) }}" enctype="multipart/form-data">
                                        @method('PUT')
                                        @csrf
                                        <div class="form-group mb-2">
                                            <label for="nom_categorie_produit" class="font-size-md text-dark font-weight-semibold mb-1">Nom Categorie span class="text-danger">*</span></label>
                                            <input type="text" class="form-control @error('nom_categorie_produit') border border-danger @enderror" id="nom_categorie_produit" value="{{$categorie->nom_categorie_produit}}" name="nom_categorie_produit" placeholder="Nom Categorie">
                                            @error('nom_categorie_produit')
                                                <div class="alert alert-danger">{{ $message }}</div>
                                            @enderror
                                        </div>
                                         <div class="form-group mb-2">
                                            <label for="photo_categorie_produit" class="font-size-md text-dark font-weight-semibold mb-1">Nom Categorie</label>
                                            <input type="file" class="form-control" id="photo_categorie_produit" name="photo_categorie_produit">
                                        </div>
                                        <button type="submit" class="btn btn-primary btn-block font-size-lg">MODIFIER</button>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="mt-auto pt-6">&copy; 2020 Thedir. All Rights Reserved.</div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/Admin/CategorieProduit/index.blade.php
@extends('layouts.app')
@section('content')
<header id="header" class="main-header header-sticky header-sticky-smart header-style-10 text-uppercase bg-white">
    <div class="header-wrapper sticky-area border-bottom">
        <div class="container-fluid">
            <nav class="navbar navbar-expand-xl">
                <div class="header-mobile d-flex d-xl-none flex-fill justify-content-between align-items-center">
                    <div class="navbar-toggler toggle-icon" data-toggle="collapse" data-target="#navbar-main-menu">
                        <span></span>
                    </div>
                    <a class="navbar-brand navbar-brand-mobile" href="{{url('/')}}">
                        <img src="{{asset('images/logo.png')}}" alt="TheDir">
                    </a>
                    <a class="mobile-button-search" href="#search-popup" data-gtf-mfp="true" data-mfp-options='{"type":"inline","mainClass":"mfp-move-from-top mfp-align-top search-popup-bg","closeOnBgClick":false,"showCloseBtn":false}'><i class="far fa-search"></i></a>
                </div>
                <div class="collapse navbar-collapse" id="navbar-main-menu">
                    <a class="navbar-brand d-none d-xl-block" href="{{url('/')}}">
                        <img src="{{asset('images/logo.png')}}" alt="TheDir">
                    </a>
                </div>
            </nav>
        </div>
    </div>
</header>

<div id="wrapper-content" class="wrapper-content pt-0 pb-0">
    <div class="page-wrapper d-flex flex-wrap flex-xl-nowrap">
        @include('Admin.Layouts.sidebar')

        <div class="page-container">
            <div class="container-fluid h-100">
                <div class="page-content-wrapper d-flex flex-column h-100">
                    <h1 class="font-size-h4 mb-4 font-weight-normal">Categorie Produit</h1>
                    <div class="page-content">
                        <div class="font-size-lg text-dark font-weight-semibold border-bottom mb-3 pb-2 lh-1">
                            <div class="row">
                                <div class="col-md-9">Listes Categorie Produit</div>
                                <div class="col-md-3">
                                    <a href="/admin/categorie-produit/create" class="btn btn-info">Nouvelle Produit</a>
                                </div>
                            </div>
                        </div>
                        <div class="table-responsive-md">
                            <table class="table">
                                <thead>
                                    <tr>
                                        <th style="width: 5%">ID</th>
                                        <th style="width: 10%">photo</th>
                                        <th style="width: 12%">NOM</th>
                                        <th style="width: 10%">SLUG</th>
                                        <th style="width: 10%">ACTION</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach($cat_produits as $cat_produit)
                                        <tr>
                                            <td><a href="panel-invoice-details.html" class="link-hover-dark-blue">CATB-00{{$cat_produit->id}}</a>
                                            </td>
                                            <td><img src="{{$cat_produit->photo_categorie_produit}}" alt="" style="width: 60px;"></td>
                                            <td>{{$cat_produit->nom_categorie_produit}}</td>
                                            <td>{{$cat_produit->slug_categorie_produit}}</td>
                                            <td>
                                                <a href="{{ route('categorie-produit.edit', [$cat_produit->id]) }}" class="btn btn-info btn-icon mb-2 mb-sm-0 font-size-md">
                                                    <i class="fa fa-edit"></i>
                                                </a>
                                                <a href="{{ route('categorie-produit.destroy', [$cat_produit->id]) }}" class="btn btn-danger btn-icon mb-2 mb-sm-0 font-size-md" data-toggle="modal" onclick="deleteData( {{ $cat_produit->id }} )" data-target="#modalDeletePack">
                                                    <i class="fa fa-trash"></i>
                                                </a>
                                            </td>
                                        </tr>
                                    @endforeach
                                </tbody>
                            </table>
                            {{$cat_produits->links()}}
                        </div>
                    </div>
                    <div class="mt-auto pt-6">&copy; 2020 Bs. All Rights Reserved.</div>
                </div>
            </div>
        </div>
    </div>
</div>

<!-- Modal -->
    <div class="modal fade" id="modalDeletePack" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
        <div class="modal-dialog modal-md modal-dialog-centered" role="document">
            <div class="modal-content">
            <div class="modal-header bg-light">
                    <h5 class="text-uppercase" id="exampleModalLongTitle"><i class="mdi mdi-account-circle mr-1"></i>
                            Suppression Pack Abonnement
                    </h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <form action="" id="deleteForm" method="post">
                    {{ csrf_field() }}
                    {{ method_field('DELETE') }}
                <div class="modal-body">
                        <p class="text-center" style="font-size:16px">Etes-vous sûr de vouloir supprimer ce la categorie ?</p>
                </div>
                <div class="modal-footer">
                    <button type="submit" class="btn btn-danger mr-1" data-dismiss="modal" onclick="formSubmit()">Supprimer</button>
                    <button type="close" class="btn btn-success" data-dismiss="modal" >Annuler</button>
                </div>
                </form>
            </div>
        </div>
    </div>

    @section('script')
    <script type=text/javascript>
        function deleteData(id)
        {
            var id = id;
            var url = '{{ route("categorie-produit.destroy", ":id") }}';
            url = url.replace(':id', id);
            $("#deleteForm").attr('action', url);
        }

        function formSubmit()
        {
            $("#deleteForm").submit();
        }
    </script>
@endsection
@endsection